CREATE TABLE "witstartuppitch_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "witstartuppitch_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "witstartuppitch_ack" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"threatEventId" varchar(255) NOT NULL,
	"actorType" varchar(64) NOT NULL,
	"actorId" varchar(128),
	"response" varchar(64) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "witstartuppitch_beach" (
	"id" varchar(64) PRIMARY KEY NOT NULL,
	"name" varchar(256) NOT NULL,
	"lat" double precision NOT NULL,
	"lng" double precision NOT NULL,
	"patrolType" varchar(32) NOT NULL,
	"councilLga" varchar(128) NOT NULL,
	"slsClub" varchar(128),
	"flagStatus" varchar(32) DEFAULT 'green' NOT NULL,
	"threatLevel" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "witstartuppitch_coordination_action" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"threatEventId" varchar(255) NOT NULL,
	"channel" varchar(64) NOT NULL,
	"status" varchar(32) DEFAULT 'pending' NOT NULL,
	"priority" integer NOT NULL,
	"message" text NOT NULL,
	"newFlagStatus" varchar(32),
	"completedAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "witstartuppitch_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "witstartuppitch_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "witstartuppitch_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "witstartuppitch_threat_event" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"beachId" varchar(64) NOT NULL,
	"type" varchar(32) NOT NULL,
	"source" varchar(128) NOT NULL,
	"confidence" double precision,
	"level" integer NOT NULL,
	"reasoning" text,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "witstartuppitch_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "witstartuppitch_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "witstartuppitch_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "witstartuppitch_account" ADD CONSTRAINT "witstartuppitch_account_userId_witstartuppitch_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."witstartuppitch_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "witstartuppitch_ack" ADD CONSTRAINT "witstartuppitch_ack_threatEventId_witstartuppitch_threat_event_id_fk" FOREIGN KEY ("threatEventId") REFERENCES "public"."witstartuppitch_threat_event"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "witstartuppitch_coordination_action" ADD CONSTRAINT "witstartuppitch_coordination_action_threatEventId_witstartuppitch_threat_event_id_fk" FOREIGN KEY ("threatEventId") REFERENCES "public"."witstartuppitch_threat_event"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "witstartuppitch_post" ADD CONSTRAINT "witstartuppitch_post_createdById_witstartuppitch_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."witstartuppitch_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "witstartuppitch_session" ADD CONSTRAINT "witstartuppitch_session_userId_witstartuppitch_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."witstartuppitch_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "witstartuppitch_threat_event" ADD CONSTRAINT "witstartuppitch_threat_event_beachId_witstartuppitch_beach_id_fk" FOREIGN KEY ("beachId") REFERENCES "public"."witstartuppitch_beach"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "witstartuppitch_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "beach_lga_idx" ON "witstartuppitch_beach" USING btree ("councilLga");--> statement-breakpoint
CREATE INDEX "action_threat_idx" ON "witstartuppitch_coordination_action" USING btree ("threatEventId");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "witstartuppitch_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "witstartuppitch_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "witstartuppitch_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "threat_beach_idx" ON "witstartuppitch_threat_event" USING btree ("beachId");