export const NB_BEACHES = [
  {
    id: "manly-south-steyne",
    name: "Manly South Steyne",
    lat: -33.7972,
    lng: 151.288,
    patrolType: "patrolled" as const,
    councilLga: "Northern Beaches",
    slsClub: "SLS Manly",
  },
  {
    id: "collins-flat",
    name: "Collins Flat",
    lat: -33.7895,
    lng: 151.281,
    patrolType: "unpatrolled" as const,
    councilLga: "Northern Beaches",
    slsClub: null,
  },
  {
    id: "dee-why",
    name: "Dee Why Beach",
    lat: -33.751,
    lng: 151.298,
    patrolType: "patrolled" as const,
    councilLga: "Northern Beaches",
    slsClub: "SLS Dee Why",
  },
  {
    id: "freshwater",
    name: "Freshwater Beach",
    lat: -33.782,
    lng: 151.294,
    patrolType: "patrolled" as const,
    councilLga: "Northern Beaches",
    slsClub: "SLS Freshwater",
  },
  {
    id: "north-narrabeen",
    name: "North Narrabeen",
    lat: -33.715,
    lng: 151.3,
    patrolType: "patrolled" as const,
    councilLga: "Northern Beaches",
    slsClub: "SLS North Narrabeen",
  },
] as const;
